server:
  port: 30000  # 设置应用端口号

spring:
  main:
    lazy-initialization: true

  datasource:
    url: jdbc:h2:tcp://127.0.0.1:30001/./QuickLauncher
    driver-class-name: org.h2.Driver
    username:
    password:

  thymeleaf:
    cache: false  # 开发环境禁用模板缓存
    prefix: classpath:/views/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

session:
  expires: 86400

application:
  version: 1.2G # 应用版本号

#用户消息、模型用户角色、模型角色、世界等隐私数据所使用的KEK
encrypt:
  kek: ${AETHER_ENCRYPT_KEK:This is not a valid KEK}
