server:
  port: 30000  # 设置应用端口号

spring:
  main:
    lazy-initialization: true

  datasource:
    url: jdbc:h2:tcp://127.0.0.1:30001/./QuickLauncher
    driver-class-name: org.h2.Driver
    username:
    password:

  thymeleaf:
    cache: false  # 开发环境禁用模板缓存
    prefix: classpath:/views/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

session:
  expires: 86400

application:
  version: 1.2N-75-M3 # 应用版本号

# 加密配置
encrypt:
  # 全局密钥加密密钥 (KEK)
  # 此密钥用于加密用户消息、模型用户角色、模型角色、世界等隐私数据。
  # 请务必妥善保管此密钥，**强烈建议使用环境变量注入，避免明文泄露**。
  # !重要：更改此密钥将导致所有使用该密钥加密的数据无法解密，造成数据永久性损毁！请务必谨慎操作。
  kek: ${AETHER_ENCRYPT_KEK:F6ztHzAFoYsldv+MepbyBp9hH/G8oG+08JmjLPh1Z5U=}
