server:
  port: 30000  # 设置应用端口号

spring:
  main:
    lazy-initialization: true

  datasource:
    url: jdbc:h2:tcp://127.0.0.1:30001/./QuickLauncher
    driver-class-name: org.h2.Driver
    username:
    password:

  thymeleaf:
    cache: false  # 开发环境禁用模板缓存
    prefix: classpath:/views/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

session:
  expires: 86400

application:
  version: 1.1Z-M9  # 应用版本号

