
ALTER TABLE USER_FILES ALTER COLUMN ORIGINAL_FILENAME RENAME TO ORIGINAL_FILE_NAME;
ALTER TABLE USER_FILES ALTER COLUMN FILEPATH RENAME TO FILE_PATH;
ALTER TABLE PLAYER ALTER COLUMN removedTime RENAME TO REMOVED_TIME;