-- 修改消息表，添加用户ID和玩家ID
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN user_id bigint COMMENT '所属用户ID';
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN player_id bigint COMMENT '所属玩家ID';

UPDATE chat_message SET user_id = -1 WHERE user_id IS NULL;
UPDATE chat_message SET player_id = -1 WHERE player_id IS NULL;

-- 更新消息表，将用户ID和玩家ID更新为会话的对应值
UPDATE CHAT_MESSAGE cm SET
    cm.USER_ID = (SELECT ct.USER_ID FROM CHAT_THREAD ct WHERE ct.ID = cm.THREAD_ID),
    cm.PLAYER_ID = (SELECT ct.PLAYER_ID FROM CHAT_THREAD ct WHERE ct.ID = cm.THREAD_ID)
WHERE
    cm.USER_ID = -1
  AND cm.PLAYER_ID = -1
  AND EXISTS (
    SELECT 1
    FROM CHAT_THREAD ct
    WHERE ct.ID = cm.THREAD_ID
);

-- 修改消息表，添加模型代码
ALTER TABLE IF EXISTS CHAT_MESSAGE ALTER COLUMN user_id bigint NOT NULL COMMENT '所属用户ID';
ALTER TABLE IF EXISTS CHAT_MESSAGE ALTER COLUMN player_id bigint NOT NULL COMMENT '所属玩家ID';
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN model_code CHARACTER VARYING(128) COMMENT '模型编码';

-- 修改消息表，移除旧版TOKEN使用量
ALTER TABLE IF EXISTS CHAT_MESSAGE DROP COLUMN token_input;
ALTER TABLE IF EXISTS CHAT_MESSAGE DROP COLUMN token_output;
ALTER TABLE IF EXISTS CHAT_MESSAGE DROP COLUMN token_thoughts;

-- 修改消息表，添加新版TOKEN使用量
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN cost_token_input INTEGER NOT NULL DEFAULT 0 COMMENT '消息TOKEN使用总量(输入)';
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN cost_token_output INTEGER NOT NULL DEFAULT 0 COMMENT '消息TOKEN使用总量(输出)';
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN token_input_text INTEGER NOT NULL DEFAULT 0 COMMENT '消息TOKEN使用量(输入文本)';
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN token_input_image INTEGER NOT NULL DEFAULT 0 COMMENT '消息TOKEN使用量(输入图片)';
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN token_input_audio INTEGER NOT NULL DEFAULT 0 COMMENT '消息TOKEN使用量(输入音频)';
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN token_output_text INTEGER NOT NULL DEFAULT 0 COMMENT '消息TOKEN使用量(输出文本)';
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN token_output_image INTEGER NOT NULL DEFAULT 0 COMMENT '消息TOKEN使用量(输出图片)';
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN token_output_audio INTEGER NOT NULL DEFAULT 0 COMMENT '消息TOKEN使用量(输出音频)';
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN token_output_thoughts INTEGER NOT NULL DEFAULT 0 COMMENT '消息TOKEN使用量(输出思考)';

-- 修改消息表，添加思考内容
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN content_thoughts TEXT COMMENT '(加密)思考内容';

-- 修改模型变体表索引：移除code字段唯一约束，为name字段添加唯一约束
DROP INDEX IF EXISTS idx_model_variant_code;
CREATE INDEX idx_model_variant_code ON model_variant(code);
CREATE UNIQUE INDEX idx_model_variant_name ON model_variant(name);

ALTER TABLE IF EXISTS CHAT_THREAD ADD COLUMN model_name CHARACTER VARYING(128);
ALTER TABLE IF EXISTS CHAT_THREAD ADD COLUMN model_variant_id BIGINT;

UPDATE CHAT_THREAD SET model_name = 'unknow';
UPDATE CHAT_THREAD SET model_code = 'unknow';
UPDATE CHAT_THREAD SET model_variant_id = -1;

ALTER TABLE IF EXISTS CHAT_THREAD ALTER COLUMN model_name CHARACTER VARYING(128) NOT NULL;
ALTER TABLE IF EXISTS CHAT_THREAD ALTER COLUMN model_variant_id BIGINT NOT NULL;

UPDATE CHAT_THREAD
SET
    MODEL_NAME = (
        SELECT NAME
        FROM PUBLIC.MODEL_VARIANT
        WHERE ENABLED = 1
        ORDER BY ID
    LIMIT 1
    ),
    MODEL_CODE = (
SELECT CODE
FROM MODEL_VARIANT
WHERE ENABLED = 1
ORDER BY ID
    LIMIT 1
    ),
    MODEL_VARIANT_ID = (
SELECT ID
FROM MODEL_VARIANT
WHERE ENABLED = 1
ORDER BY ID
    LIMIT 1
    );

