

ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN user_id bigint;
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN player_id bigint;

UPDATE chat_message SET user_id = -1 WHERE user_id IS NULL;
UPDATE chat_message SET player_id = -1 WHERE player_id IS NULL;

UPDATE CHAT_MESSAGE cm SET
    cm.USER_ID = (SELECT ct.USER_ID FROM CHAT_THREAD ct WHERE ct.ID = cm.THREAD_ID),
    cm.PLAYER_ID = (SELECT ct.PLAYER_ID FROM CHAT_THREAD ct WHERE ct.ID = cm.THREAD_ID)
WHERE
    cm.USER_ID = -1
  AND cm.PLAYER_ID = -1
  AND EXISTS (
    SELECT 1
    FROM CHAT_THREAD ct
    WHERE ct.ID = cm.THREAD_ID
);

ALTER TABLE IF EXISTS CHAT_MESSAGE ALTER COLUMN user_id bigint NOT NULL;
ALTER TABLE IF EXISTS CHAT_MESSAGE ALTER COLUMN player_id bigint NOT NULL;
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN model_code CHARACTER VARYING(128);