

ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN user_id bigint;
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN player_id bigint;

UPDATE chat_message SET user_id = -1 WHERE user_id IS NULL;
UPDATE chat_message SET player_id = -1 WHERE player_id IS NULL;

UPDATE CHAT_MESSAGE cm SET
    cm.USER_ID = (SELECT ct.USER_ID FROM CHAT_THREAD ct WHERE ct.ID = cm.THREAD_ID),
    cm.PLAYER_ID = (SELECT ct.PLAYER_ID FROM CHAT_THREAD ct WHERE ct.ID = cm.THREAD_ID)
WHERE
    cm.USER_ID = -1
  AND cm.PLAYER_ID = -1
  AND EXISTS (
    SELECT 1
    FROM CHAT_THREAD ct
    WHERE ct.ID = cm.THREAD_ID
);

ALTER TABLE IF EXISTS CHAT_MESSAGE ALTER COLUMN user_id bigint NOT NULL;
ALTER TABLE IF EXISTS CHAT_MESSAGE ALTER COLUMN player_id bigint NOT NULL;
ALTER TABLE IF EXISTS CHAT_MESSAGE ADD COLUMN model_code CHARACTER VARYING(128);

-- 修改模型变体表索引：移除code字段唯一约束，为name字段添加唯一约束
DROP INDEX IF EXISTS idx_model_variant_code;
CREATE INDEX idx_model_variant_code ON model_variant(code);
CREATE UNIQUE INDEX idx_model_variant_name ON model_variant(name);

ALTER TABLE IF EXISTS CHAT_THREAD ADD COLUMN model_name CHARACTER VARYING(128);
ALTER TABLE IF EXISTS CHAT_THREAD ADD COLUMN model_variant_id BIGINT;

UPDATE CHAT_THREAD SET model_name = 'unknow';
UPDATE CHAT_THREAD SET model_code = 'unknow';
UPDATE CHAT_THREAD SET model_variant_id = -1;

ALTER TABLE IF EXISTS CHAT_THREAD ALTER COLUMN model_name CHARACTER VARYING(128) NOT NULL;
ALTER TABLE IF EXISTS CHAT_THREAD ALTER COLUMN model_variant_id BIGINT NOT NULL;

UPDATE CHAT_THREAD
SET
    MODEL_NAME = (
        SELECT NAME
        FROM PUBLIC.MODEL_VARIANT
        WHERE ENABLED = 1
        ORDER BY ID
    LIMIT 1
    ),
    MODEL_CODE = (
SELECT CODE
FROM MODEL_VARIANT
WHERE ENABLED = 1
ORDER BY ID
    LIMIT 1
    ),
    MODEL_VARIANT_ID = (
SELECT ID
FROM MODEL_VARIANT
WHERE ENABLED = 1
ORDER BY ID
    LIMIT 1
    );

